allowBuilds:
  '@prisma/engines': true
  core-js: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  
overrides:
  '@hono/node-server': 1.19.13
  fast-xml-parser: '>=5.3.4'
  hono: '>=4.11.7'
  lodash: '>=4.17.23'
  postcss: 8.5.23
